enum ACTION_TYPES {
    FETCH_ALL_MEDIA_DATA_INIT = 'HomePage@FETCH_ALL_MEDIA_DATA_INIT',
    FETCH_ALL_MEDIA_DATA_SUCCESS = 'HomePage@FETCH_ALL_MEDIA_DATA_SUCCESS',
    FETCH_ALL_MEDIA_DATA_ERROR = 'HomePage@FETCH_ALL_MEDIA_DATA_ERROR',
  }
  export default ACTION_TYPES;
  