enum ACTION_TYPES {
    SET_ALL_MEDIA_DATA_SUCCESS = 'HomePage@SET_ALL_MEDIA_DATA_SUCCESS',
    SET_KEY_DOWN_INIT = 'HomePage@SET_KEY_DOWN_INIT',
    SET_KEY_DOWN_SUCCESS = 'HomePage@SET_KEY_DOWN_SUCCESS',
    SET_LAYOUT_OPTIONS_SUCCESS = 'HomePage@SET_LAYOUT_OPTIONS_SUCCESS'
  }
  export default ACTION_TYPES;
  