enum ACTION_TYPES {
    SET_SELECTED_AUDIO_ITEM = 'MediaPlayer@SET_SELECTED_AUDIO_ITEM',
    SET_SELECTED_NEXT_AUDIO_ITEM = 'MediaPlayer@SET_SELECTED_NEXT_AUDIO_ITEM',
    SET_SELECTED_NEXT_AUDIO_ITEM_SUCCESS = 'MediaPlayer@SET_SELECTED_NEXT_AUDIO_ITEM_SUCCESS',
    SET_SELECTED_NEXT_AUDIO_ITEM_ERROR = 'MediaPlayer@SET_SELECTED_NEXT_AUDIO_ITEM_ERROR',
    SET_SELECTED_PREVIOUS_AUDIO_ITEM = 'MediaPlayer@SET_SELECTED_PREVIOUS_AUDIO_ITEM',
    SET_SELECTED_PREVIOUS_AUDIO_ITEM_SUCCESS = 'MediaPlayer@SET_SELECTED_PREVIOUS_AUDIO_ITEM_SUCCESS',
    SET_SELECTED_PREVIOUS_AUDIO_ITEM_ERROR = 'MediaPlayer@SET_SELECTED_PREVIOUS_AUDIO_ITEM_ERROR',
}
export default ACTION_TYPES;
  