enum ACTION_TYPES {
    SET_SELECTED_AUDIO_ITEM = 'MediaPlayer@SET_SELECTED_AUDIO_ITEM',
    SET_SELECTED_NEXT_AUDIO_ITEM = 'MediaPlayer@SET_SELECTED_NEXT_AUDIO_ITEM',
    SET_SELECTED_NEXT_AUDIO_ITEM_SUCCESS = 'MediaPlayer@SET_SELECTED_NEXT_AUDIO_ITEM_SUCCESS',
}
export default ACTION_TYPES;
  